### ISSUE TITLE
Just une question

### ISSUE THREAD

**Issue by amintt2** [mrvolive/sae1.05-06#1]
Salut, desoler de deranger je voulais juste te demander pour que github pages marche et que le fichier du site web ne soit pas dans le root tu utilise un deployments doker ? il n'y a pas d'autre facons de faire ?
Merci d'avance, je te pose la question car je l'ai fais avec doker le deployments car sinons je devais renomer mon dossier src en docs. par contre je ne c'est pas comment tu a fait pour les metre dans plusieur dosier diferent. Tu utilise une autre branche ?
Merci encore

**Comment by mrvolive** [comment]
t'es parti trop loin avec ton docker, le déploiement c'est githuo pages, j'ai plus les liens mais il te faut chercher un tuto pour créer un github pages a partir d'un depot git, je sais plus trop comment on fait mais après c'est automatique

16 sept. 2024 19:49:58 Tahar Amin Touzi ***@***.***>:

**Comment by amintt2** [comment]
Ok merci je vais voir ce que je trouve
